### ISSUE TITLE
Xbox One Contoller not working

### ISSUE THREAD

**Issue by rajolm** [cathery/sys-con#146] opened 2020-03-08 09:30 UTC
Hi,
First, thank you very much for your amazing work on sys-con.

I tried to use Xbox one Controller with My Switch docked, the controller Icon appear but buttons not working.

My dock is original and my Xbox one Controller is produced at 2017 and I didn't upgrade its firmware

Is sys-con work for Xbox one Controller when Switch docked? if not, can you please tell me if you have plans to support it?

- Switch Firmware 9.1
- Atmosphere 0.10.2
- sys-con 0.5.3

**Comment by cathery** [comment] 2020-03-08 09:31
Do you have the latest firmware installed on your Xbox One Controller? If so, try holding the Xbox button so it lights up before plugging it into the dock?

**Comment by rajolm** [comment] 2020-03-08 09:36
I don't have the latest firmware, It have the original firmware, should I upgrade to latest firmware?

**Comment by cathery** [comment] 2020-03-08 09:38
There are compatibility issues caused by latest Xbox One firmware that cause the controller to not send any inputs. So no, don't update it. Xbox One Controller works docked and undocked.

**Comment by rajolm** [comment] 2020-03-08 09:40
> There are compatibility issues caused by latest Xbox One firmware that cause the controller to not send any inputs. So no, don't update it. Xbox One Controller works docked and undocked.

thank you for the quick reply,
I will give you logs today and I will be very grateful if we can found a solution for the problem

**Comment by rajolm** [comment] 2020-03-08 15:35
@cathery I have a great news!
So I have the blue special edition of Xbox one controller but it has an issue were the left trigger stuck, so, today I replace it with the normal Black Xbox one controller and the black controller works immediately!
I don't know if the special blue controller have any difference from the black one!
anyway, thank you very much again for your work on sys-con

One last question, is there any progress in Bluetooth support? it will be wonderful to get it work
is there any hope to get it soon?
:)

**Comment by cathery** [comment] 2020-03-08 15:40
Glad to hear. I wonder if Special edition controllers have something different in them from regular ones. Bluetooth support will be out when it's out.

**Comment by Alistair1231** [comment] 2020-03-08 15:53
Hey there. :)
I have a similar problem. I have a wireless Xbox One S controller (the one with bluetooth) with usb dongle which isn't picked up by the switch at all, meaning it doesn't pair. When I connect it via micro-usb cable it works fine, but not with the dongle. 

In comparison the wireless Xbox 360 controller with dongle works like a charm. 

I'm running:
- sys-con 0.5.3
- firmware 9.1.0
- Atmosphere 0.10.2 (4d5cde3)

**Comment by cathery** [comment] 2020-03-08 15:54
There's no support for Xbox One bluetooth dongle. I'm closing this thread now.

**Closed by cathery** 2020-03-08 15:54 UTC
Labels: bug
