### ISSUE TITLE
Latest firmware Xbox one controller doesn't work

### ISSUE THREAD

**Issue by andysport** [cathery/sys-con#153] opened 2020-03-24 11:57 UTC
**Description**
I update the firmware of my xbox one controller and then it doesn't work with nintendo switch in dock mode USB-link. The controller is recognized by the console but any buttons work.

**How to reproduce**
1. Update the xbox one controller at latest firmware
2. Plug with usb cable the controller to the dock
3. Go to controller menù and see that the console recognize it
4. The controller doesn't work

**Environment**
- Your Switch Firmware version 9.2.0
- Sx OS 2.9.4 beta with emunand
- latest version of Syscon

**Comment by cathery** [comment] 2020-03-24 12:01
duplicate of #100

**Closed by cathery** 2020-03-24 12:01 UTC
Labels: bug
