### ISSUE TITLE
Xbox 360 dongle support

### ISSUE THREAD

**Issue by mzino** [cathery/sys-con#11] opened 2019-11-05 20:15 UTC
I don't know if it's technically possible, but it would be great to have compatibility with the[ official Xbox 360 dongle for PC](https://support.xbox.com/en-US/xbox-on-windows/accessories/xbox-360-wireless-gaming-receiver-windows). Right now it lights up but the controller isn't recognized.

**Comment by cathery** [comment] 2019-11-05 20:33
It seems the dongle requires installing software, so i can't support it unless i get my hands on it. I made a build of the sysmodule that tries to recognize the wireless adapter as an xbox 360 controller - it's a shot in the dark, but you can try it.

https://files.catbox.moe/pwrpyl.rar

**Comment by mzino** [comment] 2019-11-05 21:16
AFAIK the drivers for the dongle are the same that you would use for the USB version of the controller, so it was worth trying. This build unfortunately still doesn't work.

**Comment by mzino** [comment] 2019-11-05 22:12
If you need logs or other info such as hardware ids etc... ask away.

**Comment by cathery** [comment] 2019-11-05 22:14
There's not much to be done right now. If you can find the vendor + product IDs of your dongle it'd be greatly appreciated

**Comment by mzino** [comment] 2019-11-05 22:18
Vendor is 045E and PID is 0719. Official MS dongle.

**Comment by mzino** [comment] 2019-11-05 22:19
Also, once paired the controller has VID 045E and PID 02A1, which I see is different from the one currently in your source for Xbox 360 USB.

**Comment by gilest** [comment] 2019-11-06 10:14
I also have a dongle. Can compile and debug if this is helpful to you

**Comment by david4444** [comment] 2019-11-06 17:59
I would do anything to make the dongle work. I can also test it, if you need it.

**Comment by gilest** [comment] 2019-11-06 21:51
Not sure if this is helpful, but I found a C++ implementation of the Xbox 360 Wireless Receiver [in the ogx360 project](https://github.com/Ryzee119/ogx360/blob/master/Firmware/ogx360_32u4/ogx360_32u4/src/libraries/USB%20Host%20Shield/XBOXRECV.cpp)

This project is GPL 👍

**Comment by Ntemis** [comment] 2019-11-07 01:48
Dongle is about $7 on AliExpress

**Comment by cathery** [comment] 2019-11-07 23:59
Can you guys launch this applet and send me a screenshot of your scanned dongles? https://files.catbox.moe/re60qo.rar

**Comment by AnthonyTorres58** [comment] 2019-11-08 00:15
![2019110719102700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45126626/68438692-eeb65080-0192-11ea-9173-c22baf28d3fc.jpg)

**Comment by gilest** [comment] 2019-11-08 00:32
### Dongle unplugged

![2019110813222700-69AA450BB058D7C0F3FABB7FC7C2DBA2](https://user-images.githubusercontent.com/36919/68439335-186f8600-022c-11ea-874f-e92708e04caa.jpg)

### Dongle plugged

![2019110813221100-69AA450BB058D7C0F3FABB7FC7C2DBA2](https://user-images.githubusercontent.com/36919/68439338-1dccd080-022c-11ea-924c-8acc66d545be.jpg)

**Comment by lukedoomer** [comment] 2019-11-08 01:05
Please add support for the popular and unofficial xbox 360 dongle as well.
Vendor:045e Product:0291
It use totally same driver with offical one.

**Comment by gilest** [comment] 2019-11-08 01:07
@lukedoomer I think that might be the one that @AnthonyTorres58 scanned. Mine is official Microsoft one I believe. Hopefully all compatible Vendor and Product ID combinations can be loaded in 😄

**Comment by cathery** [comment] 2019-11-08 01:12
Thank you all for your feedback. It seems that the dongle is using the same interface as the wireless 360 controller, which might take a while until it's implemented. Stay tuned

**Comment by orbstar8** [comment] 2019-11-08 02:34
![IMG_20191107_233005](https://user-images.githubusercontent.com/46035025/68444841-d35d3c80-01b6-11ea-8a9d-90825a65c9ca.jpg)

I share my results with the inserted adapter, apparently it gave the same results as @gilest , tested with original Xbox 360 controller

**Comment by Ntemis** [comment] 2019-11-08 05:28
@cathery note that this adapter can connect to 4 individual controllers. Also adding force feedback is mandatory for many people :)

**Comment by cathery** [comment] 2019-11-08 13:01
Can someone test if this works on their 360 wireless? https://files.catbox.moe/aw2au7.rar

**Comment by david4444** [comment] 2019-11-08 14:13
Just tested the build and the switch crashes when I try to pair the controller.
Error Code is 2168-0002 (0x4a8)
Title is 690000000000000D
On 9.0.1 With latest atmosphere.

**Comment by cathery** [comment] 2019-11-08 14:17
Can you send me the log? It's located at `sdmc:/config/sys-con/log.txt`

**Comment by david4444** [comment] 2019-11-08 14:21
[log.txt](https://github.com/cathery/sys-con/files/3824901/log.txt)

**Comment by cathery** [comment] 2019-11-08 14:25
So the dongle works fine if you just plug it and unplug it?

**Comment by david4444** [comment] 2019-11-08 14:25
> So the dongle works fine if you just plug it and unplug it?

Yeah, I can plug the dongle and unplug it. It only crashes when I attempt to pair the controller.

**Comment by cathery** [comment] 2019-11-08 15:00
Lemme know if this one works https://files.catbox.moe/30byxg.rar

**Comment by david4444** [comment] 2019-11-08 15:22
> Lemme know if this one works https://files.catbox.moe/30byxg.rar

It does. Kinda. After pairing my controller, I can move the stick and it does move, however all the buttons do not function. Also, the controller still is blinking, as if I've just turned it on. but the stick still works.

**Comment by orbstar8** [comment] 2019-11-08 15:28
> > Lemme know if this one works https://files.catbox.moe/30byxg.rar
> 
> It does. Kinda. After pairing my controller, I can move the stick and it does move, however all the buttons do not function. Also, the controller still is blinking, as if I've just turned it on. but the stick still works. As a side effect of it blinking, It will turn itself off after a while.
> UPDATE: Tried to use 2 controllers, doesn't work. it only listens to one and also, its detecting the controller as a USB controller. forgot to mention that.

The same results here, At least he recognizes it 💃

**Comment by david4444** [comment] 2019-11-08 15:31
Oh yeah, for me Y button is left stick too. Forgot to mention that. again.

**Comment by alvarin8219** [comment] 2019-11-08 16:30
gracias por trabajar en esto, de verdad se aprecia mucho tu esfuerzo, y estamos a la espera de que funcione correctamente, gracias.

**Comment by cathery** [comment] 2019-11-08 17:43
Thanks for your feedback everyone. It's a challenge to support multiple controllers under current circumstances, I'd like to make sure it works first. Please tell me if this works: https://files.catbox.moe/7htzfr.rar

**Comment by david4444** [comment] 2019-11-08 17:49
Sure, take your time with multiple. I would just like to use one, that in itself is amazing.
Testing the build now.

**Comment by david4444** [comment] 2019-11-08 17:52
Build is working perfectly! All the buttons work. Thank you! @cathery 
However, the controller is still blinking, As if its not paired. I don't know if thats a problem.
I'll test 2 controllers and edit this post.

**Comment by alvarin8219** [comment] 2019-11-08 17:56
Wow, a probar, esperemos se pueda hacer algo con múltiples controles, eres genial

**Comment by alvarin8219** [comment] 2019-11-08 18:18
Please, support to 2 controllers

**Comment by orbstar8** [comment] 2019-11-08 18:42
It works perfectly! It also provides the analogs in the switch options and also everything perfect! thanks for your great work <3

**Comment by david4444** [comment] 2019-11-08 19:19
Been playing NSMBUD, I can't feel any input lag, and the controller doesn't disconnect, so the blinking is just visual! Truly amazing.

**Comment by SageAlchemia** [comment] 2019-11-08 19:58
Works perfectly for me too! Outstanding! 0 Input lag.
The only "problem" is the blinking light... But for me is just perfect.
It would be amazing insert various controllers in 1 dongle.

**Comment by Ntemis** [comment] 2019-11-08 21:13
Great progress for one day @cathery Your done well!
Dont know if this is of any help to nail the blinking bug but here it is anw:
https://github.com/torvalds/linux/blob/master/drivers/input/joystick/xpad.c

**Comment by cathery** [comment] 2019-11-08 23:01
Can someone check if this works with multiple controllers / at all? https://files.catbox.moe/l5v1mf.rar

**Comment by gilest** [comment] 2019-11-08 23:21
That seems to work with two controllers!

**Comment by cathery** [comment] 2019-11-08 23:22
How does it work? Does it immediately connect 4 separate controllers, or only one per pairing? Does it remove the controller when unpaired?

**Comment by gilest** [comment] 2019-11-08 23:23
One per pairing. All buttons work on both controllers in the input test.

**Comment by cathery** [comment] 2019-11-08 23:23
What about the LED?

**Comment by gilest** [comment] 2019-11-08 23:24
Both flashing but I don't mind personally.

**Comment by gilest** [comment] 2019-11-08 23:24
After pairing second controller:
![2019110912240900-1E95E5926F1CB99A87326D927F27B47E](https://user-images.githubusercontent.com/36919/68517309-e4f43080-02eb-11ea-8706-4fc11e2dcda0.jpg)

**Comment by cathery** [comment] 2019-11-08 23:25
cool cool, does this version do anything to the LEDs? https://files.catbox.moe/t8x3ew.rar

**Comment by gilest** [comment] 2019-11-08 23:28
No change to LEDs. I removed and re-added the controllers and they still behave the same.

**Comment by cathery** [comment] 2019-11-08 23:28
Try this one https://files.catbox.moe/r94v38.rar

**Comment by gilest** [comment] 2019-11-08 23:31
One thing to note:

When disconnecting (removing battery) controllers after they are paired, they still show under controllers.

Removing and plugging in the dongle again resets to "No other controllers are connected".

The controllers can then be switched back on, and they will show up under controllers as they pair with the dongle.

In my opinion this is totally OK 👍 

Will try the new build now

**Comment by gilest** [comment] 2019-11-08 23:35
LED behaviour is unchanged in the new build.

**Comment by alvarin8219** [comment] 2019-11-08 23:45
Wow, Youre amazing
![IMG_20191108_174401077](https://user-images.githubusercontent.com/57537530/68517977-78c3ef00-024f-11ea-90f3-41717f699769.jpg)

**Comment by cathery** [comment] 2019-11-08 23:45
Alright, can you try this version? https://files.catbox.moe/7u3zh5.rar
Also, after unpairing the controllers, can you wait a little and see it they get disconnected under controllers?

**Comment by gilest** [comment] 2019-11-08 23:47
I waited for quite a while, I'm pretty sure that they don't. Will leave it extra long next time to make sure.

Rebooting into new build now 🚀

**Comment by gilest** [comment] 2019-11-08 23:49
LED behaviour is unchanged.

**Comment by cathery** [comment] 2019-11-08 23:56
Let's try this one https://files.catbox.moe/sw6h4l.rar

**Comment by Ntemis** [comment] 2019-11-09 00:02
Omg so much dedication! Kudos man.

**Comment by gilest** [comment] 2019-11-09 00:02
LED's are the same.

If it's helpful I can take a video of pairing one, there are some intermediate states like [looking, pairing, paired] or something.

**Comment by cathery** [comment] 2019-11-09 00:05
That's a shame. I don't think I can fix the LEDs or the disconnect for now. But I'll consider the dongle supported and close the issue.

**Comment by alvarin8219** [comment] 2019-11-09 00:11
Completamente compatible, una pena lo de los LEDS, pero has hecho un trabajo maravilloso, hoy me la pasé viendo la evolución de tu trabajo y fue increíble, saludos desde México.

**Comment by Ntemis** [comment] 2019-11-09 00:12
For your information. When 1 controller is paired the upper left led i stays green. When 2nd controller is paired the upper right is lid green. 3rd one should be down right quarter and finally 4rth is down left quarter.

**Comment by dephunk** [comment] 2019-11-09 04:48
To elaborate: see below, at the moment this does not happen. The ring just flashes, doesn't matter if you connect 1 or 4 controllers. The Xbox 1, PS3, DS4 & Wii U pro controller when connected via USB all show up with the corresponding lighting as the switch screen. 
![xboxwireless](https://user-images.githubusercontent.com/27260289/68523088-05ca7f00-0308-11ea-9dce-4152f919d13c.jpg)
Keep up the great work.

**Comment by david4444** [comment] 2019-11-09 04:51
Wow, 4 controllers! As I was sleeping? Thank you so much? Who cares about the blinking ring? The controllers are working!!

**Comment by Ntemis** [comment] 2019-11-09 05:52
@david4444 battery life should

**Comment by david4444** [comment] 2019-11-09 06:01
> @david4444 battery life should

Why? If the controllers were to be paired the light still would have been used. The blinking isn't so rapid, I doubt it would change anything.

**Comment by cathery** [comment] 2019-11-09 21:05
Can someone check if this build makes the LED blinking stop and disconnect controllers? https://files.catbox.moe/wiy7wj.rar

**Comment by gilest** [comment] 2019-11-09 21:27
Nice work, in this build the LEDs do not blink.

First controller paired: top left corner stays lit.

Second controller paired: top left corner also stays lit.

**Comment by cathery** [comment] 2019-11-09 21:29
Working as intended. The top left LED is to just disable blinking and let you know that it works (same happens with other controllers right now)

**Comment by gilest** [comment] 2019-11-09 21:31
Yeah perfect – just being thorough so you know what the behaviour is 😄

**Closed** 2019-11-09 21:42 UTC

**Comment by jamescoats** [comment] 2024-07-17 08:51
Does anyone know if this supports 2x dongles for a total of 8 players connected? I've done this in Ubuntu, so know it's technically possible.
